use std::io::Cursor;

use ark_piop::{
    SnarkBackend,
    errors::SnarkResult,
    prover::structs::proof::SNARKProof,
    setup::structs::{SNARKPk, SNARKVk},
};
use ark_serialize::{
    CanonicalDeserialize, CanonicalSerialize, Compress, SerializationError, Valid,
};
use derivative::Derivative;
use proof_planner::data_dependent_lp_optimizer::OptimizationHints;
use tracing::debug;
use tt_core::errors::TTResult;
use zstd::stream::{decode_all as zstd_decode_all, encode_all as zstd_encode_all};

pub use ark_piop::types::artifact::{Artifact, SizeBreakdown};

/// Zstd compression level used when serializing `TTProof` artifacts.
///
/// Level `1` intentionally favors low prover-side latency while still giving a
/// strong size reduction on the serialized proof bytes.
const TTPROOF_ZSTD_LEVEL: i32 = 1;

/// The full truth-table proof that is sent from the prover to the verifier
#[derive(Derivative)]
#[derivative(Clone(bound = ""))]
pub struct TTProof<B: SnarkBackend> {
    /// The SNARK proof generated by the prover, sometimes noted as "Cryptographic proof" in documentation.
    snark_proof: SNARKProof<B>,
    /// The list of optimization hints used by the prover that is sent to the verifier, which should be used by the verifier to arrive to the same proof plan as the prover.
    optimization_hints: OptimizationHints,
}

/// The prover key for the truth-table
pub struct TTPk<B: SnarkBackend> {
    /// The SNARK prover key
    snark_pk: SNARKPk<B>,
}

/// The verifier key for the truth-table
pub struct TTVk<B: SnarkBackend> {
    /// The SNARK verifier key
    snark_vk: SNARKVk<B>,
}

impl<B: SnarkBackend> TTProof<B> {
    /// Create a new TTProof from the given SNARK proof and optimization hints.
    pub fn new(
        snark_proof: SNARKProof<B>,
        optimization_hints: OptimizationHints,
    ) -> TTResult<Self> {
        Ok(Self {
            snark_proof,
            optimization_hints,
        })
    }

    /// Move the SNARK proof out of the TTProof, discarding the optimization hints.
    pub fn snark_proof(self) -> SNARKProof<B> {
        self.snark_proof
    }

    /// Get a reference to the SNARK proof contained in the TTProof.
    pub fn as_snark_proof(&self) -> &SNARKProof<B> {
        &self.snark_proof
    }
    /// Move both the SNARK proof and the optimization hints out of the TTProof.
    pub fn into_parts(self) -> (SNARKProof<B>, OptimizationHints) {
        (self.snark_proof, self.optimization_hints)
    }

    /// Get a reference to the optimization hints contained in the TTProof.
    pub fn optimization_hints(&self) -> &OptimizationHints {
        &self.optimization_hints
    }
}

impl<B> Artifact for TTVk<B>
where
    B: SnarkBackend,
{
    /// Serialize the wrapped SNARK verifier key as an uncompressed artifact.
    fn to_bytes(&self) -> SnarkResult<Vec<u8>> {
        let mut buffer = Vec::new();
        self.snark_vk.serialize_uncompressed(&mut buffer)?;
        Ok(buffer)
    }

    /// Load the wrapped SNARK verifier key from uncompressed artifact bytes.
    fn from_bytes(bytes: &[u8]) -> SnarkResult<Self> {
        let mut cursor = Cursor::new(bytes);
        Ok(Self {
            snark_vk: SNARKVk::<B>::deserialize_uncompressed_unchecked(&mut cursor)?,
        })
    }
}

impl<B> Artifact for TTPk<B>
where
    B: SnarkBackend,
    SNARKPk<B>: CanonicalSerialize + CanonicalDeserialize,
{
    /// Serialize the wrapped SNARK prover key as an uncompressed artifact.
    fn to_bytes(&self) -> SnarkResult<Vec<u8>> {
        let mut buffer = Vec::new();
        self.snark_pk.serialize_uncompressed(&mut buffer)?;
        Ok(buffer)
    }

    /// Load the wrapped SNARK prover key from uncompressed artifact bytes.
    fn from_bytes(bytes: &[u8]) -> SnarkResult<Self> {
        let mut cursor = Cursor::new(bytes);
        Ok(Self {
            snark_pk: SNARKPk::<B>::deserialize_uncompressed_unchecked(&mut cursor)?,
        })
    }
}

impl<B> Artifact for TTProof<B>
where
    B: SnarkBackend,
    SNARKProof<B>: CanonicalSerialize + CanonicalDeserialize,
{
    /// Serialize the canonical proof bytes and then zstd-compress the full artifact.
    fn to_bytes(&self) -> SnarkResult<Vec<u8>> {
        let mut raw_bytes = Vec::new();
        self.serialize_compressed(&mut raw_bytes)?;
        zstd_encode_all(Cursor::new(raw_bytes), TTPROOF_ZSTD_LEVEL).map_err(Into::into)
    }

    /// Accept either the current zstd-compressed artifact or legacy raw canonical bytes.
    fn from_bytes(bytes: &[u8]) -> SnarkResult<Self> {
        if let Ok(decoded) = zstd_decode_all(Cursor::new(bytes)) {
            let mut cursor = Cursor::new(decoded.as_slice());
            return match Self::deserialize_compressed_unchecked(&mut cursor) {
                Ok(proof) => Ok(proof),
                Err(_) => {
                    let mut fallback_cursor = Cursor::new(decoded.as_slice());
                    Ok(Self::deserialize_uncompressed_unchecked(
                        &mut fallback_cursor,
                    )?)
                }
            };
        }

        let mut cursor = Cursor::new(bytes);
        match Self::deserialize_compressed_unchecked(&mut cursor) {
            Ok(proof) => Ok(proof),
            Err(_) => {
                let mut fallback_cursor = Cursor::new(bytes);
                Ok(Self::deserialize_uncompressed_unchecked(
                    &mut fallback_cursor,
                )?)
            }
        }
    }

    /// Split the proof into its verifier hint payload and underlying SNARK proof.
    fn size_breakdown(&self) -> Option<SizeBreakdown> {
        let optimization_hints = optimization_hints_payload_bytes(&self.optimization_hints)
            .map(|bytes| bytes.len())
            .ok()?;
        let snark_proof = self.snark_proof.size_breakdown()?;

        Some(SizeBreakdown::node(
            8 + optimization_hints + snark_proof.size,
            [
                (
                    "optimization_hints",
                    SizeBreakdown::leaf(optimization_hints),
                ),
                ("snark_proof", snark_proof),
            ],
        ))
    }
}

impl<B> TTVk<B>
where
    B: SnarkBackend,
{
    /// Move the wrapped SNARK verifier key out of the front-end wrapper.
    pub fn into_inner(self) -> SNARKVk<B> {
        self.snark_vk
    }

    /// Borrow the wrapped SNARK verifier key.
    pub fn as_inner(&self) -> &SNARKVk<B> {
        &self.snark_vk
    }
}

impl<B> TTPk<B>
where
    B: SnarkBackend,
{
    /// Move the wrapped SNARK prover key out of the front-end wrapper.
    pub fn into_inner(self) -> SNARKPk<B> {
        self.snark_pk
    }

    /// Borrow the wrapped SNARK prover key.
    pub fn as_inner(&self) -> &SNARKPk<B> {
        &self.snark_pk
    }
}

/// Serialize optimization hints into the framed payload embedded inside `TTProof`.
///
/// The `TTH1` prefix marks the payload as optimization hints so deserialization
/// can distinguish it from the legacy slot that used to contain optimized IR bytes.
fn optimization_hints_payload_bytes(
    optimization_hints: &OptimizationHints,
) -> Result<Vec<u8>, SerializationError> {
    if optimization_hints.is_empty() {
        return Ok(Vec::new());
    }
    let payload = bincode::serialize(optimization_hints).map_err(|err| {
        debug!(
            ?err,
            "TTProof serialize: failed to serialize optimization hints"
        );
        SerializationError::InvalidData
    })?;
    let mut bytes = Vec::with_capacity(b"TTH1".len() + payload.len());
    bytes.extend_from_slice(b"TTH1");
    bytes.extend_from_slice(&payload);
    Ok(bytes)
}

/// Implementing the Valid trait for `TTProof` to allow for validation checks during deserialization if needed.
impl<B> Valid for TTProof<B>
where
    B: SnarkBackend,
{
    fn check(&self) -> Result<(), SerializationError> {
        Ok(())
    }
}

/// Canonical serialization for `TTProof`.
///
/// The serialized layout is:
/// 1. little-endian payload length for optimization hints
/// 2. framed optimization-hint payload bytes
/// 3. canonical SNARK proof bytes
impl<B> CanonicalSerialize for TTProof<B>
where
    B: SnarkBackend,
    SNARKProof<B>: CanonicalSerialize,
{
    fn serialize_with_mode<W: std::io::Write>(
        &self,
        mut writer: W,
        compress: Compress,
    ) -> Result<(), SerializationError> {
        let plan_bytes = optimization_hints_payload_bytes(&self.optimization_hints)?;
        let plan_len = plan_bytes.len() as u64;
        debug!(
            plan_len,
            "TTProof serialize: optimization-hint artifact byte length"
        );
        writer.write_all(&plan_len.to_le_bytes())?;
        writer.write_all(&plan_bytes)?;
        self.snark_proof
            .serialize_with_mode(&mut writer, compress)?;
        Ok(())
    }

    fn serialized_size(&self, compress: Compress) -> usize {
        let plan_len = optimization_hints_payload_bytes(&self.optimization_hints)
            .map(|bytes| bytes.len())
            .unwrap_or(0);
        8 + plan_len + self.snark_proof.serialized_size(compress)
    }
}

/// Canonical deserialization for `TTProof`.
///
/// New proofs decode optimization hints from the framed payload. Older proofs
/// may still have bytes in that slot that are ignored for backward compatibility.
impl<B> CanonicalDeserialize for TTProof<B>
where
    B: SnarkBackend,
    SNARKProof<B>: CanonicalDeserialize,
{
    fn deserialize_with_mode<R: std::io::Read>(
        mut reader: R,
        compress: ark_serialize::Compress,
        _validate: ark_serialize::Validate,
    ) -> Result<Self, SerializationError> {
        let mut len_bytes = [0u8; 8];
        reader.read_exact(&mut len_bytes)?;
        let plan_len = u64::from_le_bytes(len_bytes) as usize;
        let mut plan_bytes = vec![0u8; plan_len];
        if plan_len > 0 {
            reader.read_exact(&mut plan_bytes)?;
        }
        let optimization_hints = if plan_len == 0 {
            OptimizationHints::default()
        } else if plan_bytes.starts_with(b"TTH1") {
            bincode::deserialize::<OptimizationHints>(&plan_bytes[b"TTH1".len()..])
                .map_err(|_| SerializationError::InvalidData)?
        } else {
            // Legacy proofs stored optimized IR bytes in this slot. We keep the
            // framing compatible, but new code no longer retains that payload.
            OptimizationHints::default()
        };
        let snark_proof = SNARKProof::<B>::deserialize_with_mode(reader, compress, _validate)?;
        Ok(Self {
            snark_proof,
            optimization_hints,
        })
    }
}
