[package]
name = "zk_sql"
version = "0.1.0"
edition = "2021"

[dependencies]
kit = { path = "../kit" }
transcript = { path = "../transcript" }
arithmetic = { path = "../arithmetic" }
crypto = { path = "../crypto" }
sumcheck = { path = "../sumcheck" }
rand_chacha = { version = "0.3.0", default-features = false }
uuid = { version = "1.2", features = ["v4"] }
datafusion = "43.0.0"
tokio = { version = "^1.41.0", features = ["rt", "macros", "rt-multi-thread"] }
zksql-macros = { path = "../zksql-macros" }

[dev-dependencies]
ark-test-curves = { version = "0.5.0", default-features = false, features = [
    "bls12_381_curve",
] }


[features]
default = ["parallel"]
# extensive sanity checks that are useful for debugging
extensive_sanity_checks = []
parallel = [
    "kit/parallel",
    "crypto/parallel",
    "arithmetic/parallel",
    "transcript/parallel",
    "sumcheck/parallel"
]
print-trace = ["kit/print-trace"]

# [[bench]]
# name = "select-feas-benches"
# harness = false


# [[bench]]
# name = "groupby-feas-benches"
# harness = false
