/// The Tracker is a data structure for creating and managing virtual
/// polynomials and their commitments. It is in charge of  
///                      1) Recording the structure of virtual polynomials and
///                         their products
///                      2) Recording the structure of virtual polynomials and
///                         their products
///                      3) Recording the commitments of virtual polynomials and
///                         their products
///                      4) Providing methods for adding virtual polynomials
///                         together
use std::{collections::HashMap, ops::Neg, panic, sync::Arc};

use arithmetic::mle::mat::{dmle_increase_nv_back, dmle_increase_nv_front};
use arithmetic::mle::virt::{build_eq_x_r, VirtualPolynomial};
use crypto::ark_ec::pairing::Pairing;
use arithmetic::ark_ff::{Field, PrimeField};
use arithmetic::ark_poly::{DenseMultilinearExtension, MultilinearExtension};
use crypto::pcs::PolynomialCommitmentScheme;
use kit::ark_serialize::CanonicalSerialize;
use kit::ark_std::{One, Zero};
use kit::rayon::vec;

use crypto::pcs::prelude::PCSError;
use sumcheck::sum_check::SumCheck;
use sumcheck::PolyIOP;
use crate::tracker::{
    errors::PolyIOPErrors,
    // pcs_accumulator::PcsAccumulator;
    tracker_structs::{CompiledZKSQLProof, TrackerID, TrackerSumcheckClaim, TrackerZerocheckClaim},
};


use kit::derivative::Derivative;
use kit::displaydoc::Display;


use transcript::{Tr, TranscriptError};

use arithmetic::ark_poly::Polynomial;

type PolyMap<P> = HashMap<TrackerID, P>;
type VirtualPoly<F> = Vec<(F, Vec<TrackerID>)>;
// Clone is only implemented if PCS satisfies the PolynomialCommitmentScheme<F>
// bound, which guarantees that PCS::ProverParam
#[derive(Derivative, Display)]
#[derivative(Clone(bound = "PCS: PolynomialCommitmentScheme<F>"))]
pub struct ProverTracker<F: PrimeField, PCS: PolynomialCommitmentScheme<F>>
where
    F: PrimeField,
{
    /// The PCS parameters for the prover; e.g. the number of vriables, srs,
    /// etc.
    pub pcs_param: PCS::ProverParam,

    /// The transcript for the PIOP
    pub transcript: Tr<F>,

    /// number of the tracked polynomials
    pub num_tracked_polys: usize,
    /// A map from TrackerID to a reference materialized polynomials, i.e.
    /// polynomials that are explicitely stored
    pub materialized_polys: PolyMap<Arc<DenseMultilinearExtension<F>>>,
    /// A map from TrackerID to a virtual polynomials, i.e. polynomials of the
    /// form `sum_i c_i * prod_j p_ij` where `p_ij` points to another
    /// materialized or virtual polynomials
    pub virtual_polys: PolyMap<VirtualPoly<F>>,
    /// A map from TrackerID to the commitment of the polynomial
    pub materialized_comms: HashMap<TrackerID, PCS::Commitment>,
    /// A list of all sumcheck claims
    pub sum_check_claims: Vec<TrackerSumcheckClaim<F>>,
    /// A list of all zerocheck claims, this will be compiled into sumcheck
    /// claims at the end
    // TODO: Can't we immediately convert the zerocheck claims into sumcheck claims? and get rid of
    // zero_check_claims?
    pub zero_check_claims: Vec<TrackerZerocheckClaim<F>>,
}

impl<F: PrimeField, PCS: PolynomialCommitmentScheme<F>> ProverTracker<F, PCS>
where
    F: PrimeField,
{
    pub fn new(pcs_param: PCS::ProverParam) -> Self {
        Self {
            pcs_param,
            transcript: Tr::<F>::new(b"Initializing Tracnscript"),
            num_tracked_polys: 0,
            virtual_polys: HashMap::new(),
            materialized_polys: HashMap::new(),
            materialized_comms: HashMap::new(),
            sum_check_claims: Vec::new(),
            zero_check_claims: Vec::new(),
        }
    }

    /// Generates a new `TrackerID`.
    ///
    /// This function increments an internal counter and returns a new
    /// `TrackerID` based on the current value of the counter. It ensures
    /// that each generated `TrackerID` is unique.
    pub fn gen_id(&mut self) -> TrackerID {
        let id = self.num_tracked_polys;
        self.num_tracked_polys += 1;
        TrackerID(id)
    }

    /// Peek at the next `TrackerID` that will be generated by gen_id.
    pub fn get_next_id(&mut self) -> TrackerID {
        TrackerID(self.num_tracked_polys)
    }

    /// Tracks a materialized polynomial.
    ///
    /// moves the polynomial to heap, assigns a TracckerID to it in map and
    /// returns the TrackerID
    pub fn track_mat_poly(&mut self, polynomial: DenseMultilinearExtension<F>) -> TrackerID {
        let polynomial = Arc::new(polynomial);
        self.track_mat_arc_poly(polynomial)
    }

    /// Tracks materialized polynomial by reference.
    ///
    /// Assumes the input polynomial is already on the heap and assigns a
    /// TrackerID to it in the map
    fn track_mat_arc_poly(&mut self, polynomial: Arc<DenseMultilinearExtension<F>>) -> TrackerID {
        // Create the new TrackerID
        let poly_id = self.gen_id();

        // Add the polynomial to the materialized map
        self.materialized_polys.insert(poly_id, polynomial.clone());

        // Return the new TrackerID
        poly_id
    }

    /// Tracks a materialized polynomial and sends a commitment to the verifier.
    pub fn track_and_commit_mat_poly(
        &mut self,
        polynomial: DenseMultilinearExtension<F>,
    ) -> Result<TrackerID, PCSError> {
        // commit to the polynomial
        let commitment = PCS::commit(self.pcs_param.clone(), &polynomial)?;

        // track the polynomial and get its id
        let poly_id = self.track_mat_poly(polynomial);

        // add the commitment to the commitment map with the same poly_id
        self.materialized_comms.insert(poly_id, commitment.clone());

        // Add the commitment to the transcript, since it will be sent to the verifier
        self.transcript
            .append_serializable_element(b"comm", &commitment)?;

        // Return the new TrackerID
        Ok(poly_id)
    }

    /// Tracks a virtual polynomial
    ///
    /// generates a new TrackerID and adds the virtual polynomial to the map
    fn track_virt_poly(&mut self, virt: VirtualPoly<F>) -> TrackerID {
        let poly_id = self.gen_id();
        self.virtual_polys.insert(poly_id, virt);
        // No need to commit to virtual polynomials
        poly_id
    }

    /// Get a reference to a materialized polynomial on the heap, from the map,
    /// by its TrackerID
    pub fn get_mat_poly(&self, id: TrackerID) -> Option<&Arc<DenseMultilinearExtension<F>>> {
        self.materialized_polys.get(&id)
    }

    /// Get a virtual polynomial, from the map, by its TrackerID
    pub fn get_virt_poly(&self, id: TrackerID) -> Option<&VirtualPoly<F>> {
        self.virtual_polys.get(&id)
    }

    /// Get the number of variables of a polynomial, by its TrackerID
    pub fn get_poly_nv(&self, id: TrackerID) -> usize {
        // If it's materialized, simply return the number of variables
        let mat_poly = self.materialized_polys.get(&id);

        if let Some(mat_poly) = mat_poly {
            return mat_poly.num_vars();
        }

        // look up the virtual polynomial
        let virt_poly = self.virtual_polys.get(&id);
        if virt_poly.is_none() {
            panic!("Unknown poly id: {:?}", id);
        }
        let virt_poly: &VirtualPoly<F> = virt_poly.unwrap(); // Invariant: contains only material PolyIDs //TODO: Why?

        // TODO: Wouldn't it be better to store the number of variables in the virtual
        // polynomial?
        // figure out the number of variables, assume they all have
        // this nv Get the nv from the first polynomial of the first term of the
        // virtual polynomial This polynomial might itself be virtual, so we
        // need to recurse
        let first_id = virt_poly[0].1[0];
        let nv: usize = self.get_mat_poly(first_id).unwrap().num_vars();
        nv
    }

    /// Adds/Subtracts two polynomials together
    /// The two polynomials are identified by their TrackerIDs, Each one can be
    /// either materialized or virtual
    /// The output is a tracker to a new virtual polynomial
    pub fn add_sub_polys(&mut self, p1_id: TrackerID, p2_id: TrackerID, do_sub: bool) -> TrackerID {
        let sign_coeff: F = if do_sub { F::one().neg() } else { F::one() };

        let p1_mat = self.get_mat_poly(p1_id);
        let p1_virt = self.get_virt_poly(p1_id);
        let p2_mat = self.get_mat_poly(p2_id);
        let p2_virt = self.get_virt_poly(p2_id);

        let mut new_virt_rep: VirtualPoly<F> = Vec::new(); // Invariant: contains only material TrackerIDs
        match (
            p1_mat.is_some(),
            p1_virt.is_some(),
            p2_mat.is_some(),
            p2_virt.is_some(),
        ) {
            // Bad Case: p1 not found
            (false, false, ..) => {
                panic!("Unknown p1 TrackerID {:?}", p1_id);
            },
            // Bad Case: p2 not found
            (_, _, false, false) => {
                panic!("Unknown p2 TrackerID {:?}", p2_id);
            },
            // Case 1: both p1 and p2 are materialized
            (true, false, true, false) => {
                new_virt_rep.push((F::one(), vec![p1_id]));
                new_virt_rep.push((sign_coeff, vec![p2_id]));
            },
            // Case 2: p1 is materialized and p2 is virtual
            (true, false, false, true) => {
                new_virt_rep.push((F::one(), vec![p1_id]));
                p2_virt.unwrap().iter().for_each(|(coeff, prod)| {
                    new_virt_rep.push((sign_coeff * *coeff, prod.clone()));
                });
            },
            // Case 3: p2 is materialized and p1 is virtual
            (false, true, true, false) => {
                p1_virt.unwrap().iter().for_each(|(coeff, prod)| {
                    new_virt_rep.push((*coeff, prod.clone()));
                });
                new_virt_rep.push((sign_coeff, vec![p2_id]));
            },
            // Case 4: both p1 and p2 are virtual
            (false, true, false, true) => {
                p1_virt.unwrap().iter().for_each(|(coeff, prod)| {
                    new_virt_rep.push((*coeff, prod.clone()));
                });
                p2_virt.unwrap().iter().for_each(|(coeff, prod)| {
                    new_virt_rep.push((sign_coeff * *coeff, prod.clone()));
                });
            },
            // Handling unexpected cases
            _ => {
                panic!("Internal tracker::add_polys error. This code should be unreachable");
            },
        }
        self.track_virt_poly(new_virt_rep)
    }

    /// Adds two polynomials together
    /// The two polynomials are identified by their TrackerIDs, Each one can be
    /// either materialized or virtual
    /// The output is a tracker to a new virtual polynomial
    pub fn add_polys(&mut self, p1_id: TrackerID, p2_id: TrackerID) -> TrackerID {
        self.add_sub_polys(p1_id, p2_id, false)
    }

    /// Subtracts p2 from p1
    /// The two polynomials are identified by their TrackerIDs, Each one can be
    /// either materialized or virtual
    /// The output is a tracker to a new virtual polynomial
    pub fn sub_polys(&mut self, p1_id: TrackerID, p2_id: TrackerID) -> TrackerID {
        self.add_sub_polys(p1_id, p2_id, true)
    }

    /// Multiplies two polynomials together
    /// The two polynomials are identified by their TrackerIDs, Each one can be
    /// either materialized or virtual
    /// The output is a tracker to a new virtual polynomial
    pub fn mul_polys(&mut self, p1_id: TrackerID, p2_id: TrackerID) -> TrackerID {
        let p1_mat = self.get_mat_poly(p1_id);
        let p1_virt = self.get_virt_poly(p1_id);
        let p2_mat = self.get_mat_poly(p2_id);
        let p2_virt = self.get_virt_poly(p2_id);

        let mut new_virt_rep = Vec::new(); // Invariant: contains only material TrackerIDs
        match (
            p1_mat.is_some(),
            p1_virt.is_some(),
            p2_mat.is_some(),
            p2_virt.is_some(),
        ) {
            // Bad Case: p1 not found
            (false, false, ..) => {
                panic!("Unknown p1 TrackerID {:?}", p1_id);
            },
            // Bad Case: p2 not found
            (_, _, false, false) => {
                panic!("Unknown p2 TrackerID {:?}", p2_id);
            },
            // Case 1: both p1 and p2 are materialized
            (true, false, true, false) => {
                new_virt_rep.push((F::one(), vec![p1_id, p2_id]));
            },
            // Case 2: p1 is materialized and p2 is virtual
            (true, false, false, true) => {
                let p2_rep = p2_virt.unwrap();
                p2_rep.iter().for_each(|(coeff, prod)| {
                    let mut new_prod = prod.clone();
                    new_prod.push(p1_id);
                    new_virt_rep.push((*coeff, new_prod));
                });
            },
            // Case 3: p2 is materialized and p1 is virtual
            (false, true, true, false) => {
                let p1_rep = p1_virt.unwrap();
                p1_rep.iter().for_each(|(coeff, prod)| {
                    let mut new_prod = prod.clone();
                    new_prod.push(p2_id);
                    new_virt_rep.push((*coeff, new_prod));
                });
            },
            // Case 4: both p1 and p2 are virtual
            (false, true, false, true) => {
                let p1_rep = p1_virt.unwrap();
                let p2_rep = p2_virt.unwrap();
                p1_rep.iter().for_each(|(p1_coeff, p1_prod)| {
                    p2_rep.iter().for_each(|(p2_coeff, p2_prod)| {
                        let new_coeff = *p1_coeff * p2_coeff;
                        let mut new_prod_vec = p1_prod.clone();
                        new_prod_vec.extend(p2_prod.clone());
                        new_virt_rep.push((new_coeff, new_prod_vec));
                    })
                });
            },
            // Handling unexpected cases
            _ => {
                panic!("Internal tracker::mul_polys error. This code should be unreachable");
            },
        }
        self.track_virt_poly(new_virt_rep)
    }

    /// Adds a scalar to a polynomial, returns a new virtual polynomial
    // TODO: Can we do it more efficiently?
    pub fn add_scalar(&mut self, poly_id: TrackerID, c: F) -> TrackerID {
        let nv = self.get_poly_nv(poly_id);
        let scalar_mle =
            DenseMultilinearExtension::from_evaluations_vec(nv, vec![c; 2_usize.pow(nv as u32)]);
        let scalar_id = self.track_mat_poly(scalar_mle);
        self.add_polys(poly_id, scalar_id)
    }

    /// Multiplies a polynomial by a scalar, returns a new virtual polynomial
    pub fn mul_scalar(&mut self, poly_id: TrackerID, c: F) -> TrackerID {
        let mut new_virt_rep = Vec::new(); // Invariant: contains only material TrackerIDs

        let p_mat = self.get_mat_poly(poly_id);
        if p_mat.is_some() {
            new_virt_rep.push((c, vec![poly_id]));
        } else {
            let p_virt = self.get_virt_poly(poly_id);
            p_virt.unwrap().iter().for_each(|(coeff, prod)| {
                new_virt_rep.push((*coeff * c, prod.clone()));
            });
        }
        self.track_virt_poly(new_virt_rep)
    }

    // TODO: I don't understand what this function does
    pub fn increase_nv_front(&mut self, poly_id: TrackerID, added_nv: usize) -> TrackerID {
        self.materialize_poly(poly_id);
        let base_mle = self.get_mat_poly(poly_id).unwrap();
        let base_nv = base_mle.num_vars();
        let res_mle = dmle_increase_nv_front(base_mle, base_nv + added_nv);
        self.track_mat_arc_poly(res_mle)
    }
    // TODO: I don't understand what this function does
    pub fn increase_nv_back(&mut self, poly_id: TrackerID, added_nv: usize) -> TrackerID {
        self.materialize_poly(poly_id);
        let base_mle = self.get_mat_poly(poly_id).unwrap();
        let base_nv = base_mle.num_vars();
        let res_mle = dmle_increase_nv_back(base_mle, base_nv + added_nv);
        self.track_mat_arc_poly(res_mle)
    }

    /// Materializes a polynomial in-place
    /// The polynomial will be stored in the heap
    fn materialize_poly(&mut self, id: TrackerID) {
        // look up the virtual polynomial
        let mat_poly = self.materialized_polys.get(&id);
        if mat_poly.is_some() {
            return; // already materialized
        }
        let virt_poly = self.virtual_polys.get(&id);
        if virt_poly.is_none() {
            panic!("Unknown poly id: {:?}", id);
        }
        let virt_poly = virt_poly.unwrap().clone(); // Invariant: contains only material PolyIDs

        // figure out the number of variables, assume they all have this nv
        let first_id = virt_poly[0].1[0].clone();
        let nv: usize = self.get_mat_poly(first_id).unwrap().num_vars();

        // calculate the evaluation of each product list
        let prod_evaluations: Vec<Vec<F>> = virt_poly
            .iter()
            .map(|(coeff, prod)| {
                let mut res = vec![coeff.clone(); 2_usize.pow(nv as u32)];
                prod.iter().for_each(|poly| {
                    let poly_evals = self.evaluations(*poly);
                    res = res
                        .iter()
                        .zip(poly_evals.iter())
                        .map(|(a, b)| *a * b)
                        .collect()
                });
                res
            })
            .collect();

        // sum the evaluations of each product list
        let mut evals = vec![F::zero(); 2_usize.pow(nv as u32)];
        prod_evaluations.iter().for_each(|prod_eval| {
            evals = evals
                .iter()
                .zip(prod_eval.iter())
                .map(|(a, b)| *a + b)
                .collect()
        });

        // cache the result by updating the materialized poly map
        let mle = Arc::new(DenseMultilinearExtension::from_evaluations_vec(nv, evals));
        self.materialized_polys.insert(id.clone(), mle);
        self.virtual_polys.remove(&id);
    }

    /// Evaluates a polynomial at a point
    pub fn evaluate(&self, id: TrackerID, pt: &[F]) -> Option<F> {
        // if the poly is materialized, return the evaluation
        let mat_poly = self.materialized_polys.get(&id);
        // TODO: Change this to_vec
        if mat_poly.is_some() {
            return Some(mat_poly.unwrap().evaluate(&pt.to_vec()));
        }

        // look up the virtual polynomial
        let virt_poly = self.virtual_polys.get(&id);
        if virt_poly.is_none() {
            panic!("Unknown poly id: {:?}", id);
        }
        let virt_poly = virt_poly.unwrap(); // Invariant: contains only material TrackerIDs

        // calculate the evaluation of each product list
        let prod_evals: Vec<F> = virt_poly
            .iter()
            .map(|(coeff, prod)| {
                let mut res = coeff.clone();
                prod.iter().for_each(|poly| {
                    res *= self.evaluate(poly.clone(), pt).unwrap();
                });
                res
            })
            .collect();

        // sum the evaluations of each product list
        let mut eval = F::zero();
        prod_evals.iter().for_each(|prod_eval| {
            eval += prod_eval;
        });

        // return the eval
        Some(eval)
    }

    /// Returns the evaluations of a polynomial on the boolean hypercube
    pub fn evaluations(&mut self, id: TrackerID) -> &Vec<F> {
        self.materialize_poly(id);
        let mat_poly = self.materialized_polys.get(&id).unwrap();
        &mat_poly.evaluations
    }

    /// Generate the challenge from the current transcript
    /// and append it to the transcript.
    pub fn get_and_append_challenge(&mut self, label: &'static [u8]) -> Result<F, TranscriptError> {
        self.transcript.get_and_append_challenge(label)
    }

    /// Append the message to the transcript.
    pub fn append_serializable_element<S: CanonicalSerialize>(
        &mut self,
        label: &'static [u8],
        group_elem: &S,
    ) -> Result<(), TranscriptError> {
        self.transcript
            .append_serializable_element(label, group_elem)
    }

    /// Adds a sumcheck claim to the list of the sumcheck claims of the prover
    /// a sumcheck claim is of the form (poly_id, claimed_sum) which means that
    /// the prover claims that the sum of the evaluations of the polynomial with
    /// poly_id is claimed_sum
    pub fn add_sumcheck_claim(&mut self, poly_id: TrackerID, claimed_sum: F) {
        self.sum_check_claims
            .push(TrackerSumcheckClaim::new(poly_id, claimed_sum));
    }

    /// Adds a zerocheck claim to the list of the zerocheck claims of the prover
    /// a zerocheck claim is of the form (poly_id) which means that the prover
    /// claims that the polynomial with poly_id evaluates to zero all over the
    /// boolean hypercube
    pub fn add_zerocheck_claim(&mut self, poly_id: TrackerID) {
        self.zero_check_claims
            .push(TrackerZerocheckClaim::new(poly_id));
    }

    pub fn add_fold_claim(&mut self, folded: TrackerID, poly_id: &[TrackerID], challs: &[F]) {
        let mut new_virt_rep = Vec::new(); // Invariant: contains only material TrackerIDs
        for (poly_id, chall) in poly_id.iter().zip(challs.iter()) {
            new_virt_rep.push((chall.clone(), vec![poly_id.clone()]));
        }
        new_virt_rep.push((-F::one(), vec![folded]));
        let id = self.track_virt_poly(new_virt_rep);
        self.add_zerocheck_claim(id);
    }

    // TODO: Is this only used to be compatible with the hyperplonk code?
    pub fn to_arithmatic_virtual_poly(&self, id: TrackerID) -> VirtualPolynomial<F> {
        let mat_poly = self.materialized_polys.get(&id);
        if mat_poly.is_some() {
            return VirtualPolynomial::new_from_mle(mat_poly.unwrap(), F::one());
        }

        let poly = self.virtual_polys.get(&id);
        if poly.is_none() {
            panic!("Unknown poly id: {:?}", id);
        }
        let poly = poly.unwrap(); // Invariant: contains only material PolyIDs
        let first_id = poly[0].1[0].clone();
        let nv: usize = self.get_mat_poly(first_id).unwrap().num_vars();

        let mut arith_virt_poly: VirtualPolynomial<F> = VirtualPolynomial::new(nv);
        for (prod_coef, prod) in poly.iter() {
            let prod_mle_list = prod
                .iter()
                .map(|poly_id| self.get_mat_poly(poly_id.clone()).unwrap().clone())
                .collect::<Vec<Arc<DenseMultilinearExtension<F>>>>();
            arith_virt_poly
                .add_mle_list(prod_mle_list, prod_coef.clone())
                .unwrap();
        }

        arith_virt_poly
    }

    /// Iterates through the materialized polynomials and increases the number
    /// of variables to the max number of variables in the tracker
    /// Used as a preprocessing step before batching polynomials,
    fn equalize_materialized_poly_nv(&mut self) -> usize {
        // calculate the max nv
        let nv: usize = self
            .materialized_polys
            .iter()
            .map(|(_, p)| p.num_vars())
            .max()
            .ok_or(1)
            .unwrap();

        // increase the nv of all the polynomials
        for (_, poly) in self.materialized_polys.iter_mut() {
            let old_nv = poly.num_vars();
            if old_nv != nv {
                *poly = dmle_increase_nv_back(poly, nv); // increase_nv_back and
                                                         // increase_nv_front
                                                         // are equivalent, they
                                                         // cause the same sums,
                                                         // just be consistent
            }
        }

        // need to update the claims because resizing messes stuff up
        let old_sumcheck_claims = self.sum_check_claims.clone();
        let true_sums: Vec<F> = old_sumcheck_claims
            .iter()
            .map(|claim| self.evaluations(claim.label.clone()).iter().sum::<F>())
            .collect();
        for (claim, &true_sum) in self.sum_check_claims.iter_mut().zip(true_sums.iter()) {
            claim.claimed_sum = true_sum;
        }

        nv
    }

    /// converts the zerocheck claims into a sumcheck claim
    fn convert_zerocheck_claims_to_sumcheck_claim(&mut self, nv: usize) {
        // 1) aggregate the zerocheck claims into a single MLE
        let mut zerocheck_agg_poly =
            self.track_mat_poly(DenseMultilinearExtension::<F>::from_evaluations_vec(
                nv,
                vec![F::zero(); 2_usize.pow(nv as u32)],
            ));
        let zero_check_claims = self.zero_check_claims.clone();
        for claim in zero_check_claims {
            let challenge = self
                .get_and_append_challenge(b"zerocheck challenge")
                .unwrap();
            let claim_poly_id = self.mul_scalar(claim.label.clone(), challenge);
            zerocheck_agg_poly = self.add_polys(zerocheck_agg_poly, claim_poly_id);
        }

        // sample r
        let r = self
            .transcript
            .get_and_append_challenge_vectors(b"0check r", nv)
            .unwrap();

        // build the eq(x, r) polynomial
        let eq_x_r = build_eq_x_r(r.as_ref()).unwrap();
        let eq_x_r_id = self.track_mat_arc_poly(eq_x_r); // do not need to commit, verifier builds their own

        // create the relevant sumcheck claim
        let new_sc_claim_poly = self.mul_polys(zerocheck_agg_poly, eq_x_r_id); // Note: SumCheck val should be zero
        self.add_sumcheck_claim(new_sc_claim_poly, F::zero());
    }

    /// creates a finished proof based off the subclaims that have been recorded
    /// 1) aggregates the subclaims into a single MLE
    /// 2) generates a sumcheck proof
    /// 3) create a batch opening proofs for the sumcheck point
    /// 4) takes all relevant stuff and returns a CompiledProof
    pub fn compile_proof(&mut self) -> Result<CompiledZKSQLProof<F, PCS>, PolyIOPErrors> {
        let max_nv = self.equalize_materialized_poly_nv();

        // 1) aggregate the zerocheck claims into a single MLE Then convert the
        //    zerocheck_agg_poly to a sumcheck
        self.convert_zerocheck_claims_to_sumcheck_claim(max_nv); // Note: SumCheck val should be zero

        // 1.5) aggregate the sumcheck claims
        // Instead of proving p_1 = s_1, p_2 = s_2, ... p_n = s_n, we prove
        // We prove c_1 * p_1 + c_2 * p_2 + ... + c_n * p_n = c_1 * s_1 + c_2 * s_2 +
        // ... + c_n * s_n where c_i-s are random challenges
        let mut sumcheck_poly =
            self.track_mat_poly(DenseMultilinearExtension::<F>::from_evaluations_vec(
                max_nv,
                vec![F::zero(); 2_usize.pow(max_nv as u32)],
            ));
        let mut sc_sum = F::zero();

        // TODO: This can be done more efficiently
        for claim in self.sum_check_claims.clone().iter() {
            let challenge = self
                .get_and_append_challenge(b"sumcheck challenge")
                .unwrap();
            let claim_times_challenge_id = self.mul_scalar(claim.label.clone(), challenge);
            sumcheck_poly = self.add_polys(sumcheck_poly, claim_times_challenge_id);
            sc_sum += claim.claimed_sum * challenge;
        }

        // 2) generate a sumcheck proof
        #[cfg(debug_assertions)]
        {
            let true_agg_sum: F = self.evaluations(sumcheck_poly.clone()).iter().sum::<F>();
            if true_agg_sum != sc_sum {
                // this usually happens becuase of a bug related to equalizing the nv
                let err_msg = "prover_tracker::compile_proof error: true_agg_sum != sc_sum";
                return Err(PolyIOPErrors::InvalidProver(err_msg.to_string()));
            }
        }
        let sc_avp = self.to_arithmatic_virtual_poly(sumcheck_poly);
        let sc_aux_info = sc_avp.aux_info.clone();
        let sc_proof = <PolyIOP<F> as SumCheck<F>>::prove(&sc_avp, &mut self.transcript).unwrap();
        
        // 3) create a batch opening proofs for the sumcheck point iterate over sc_avp,
        //    grab comms, run PCS batch open, get the proofs
        let sumcheck_point = sc_proof.point.clone();
        let mut mat_comm_ids = self
            .materialized_comms
            .keys()
            .cloned()
            .collect::<Vec<TrackerID>>();
        mat_comm_ids.sort(); // sort so the transcript is generated consistently
        let mut mat_polys = Vec::with_capacity(mat_comm_ids.len());
        let mut points = Vec::with_capacity(mat_comm_ids.len());
        let mut evals = Vec::with_capacity(mat_comm_ids.len());
        mat_comm_ids.iter().for_each(|id| {
            let poly = self.get_mat_poly(id.clone()).unwrap().clone();
            let eval = poly.evaluate(&sumcheck_point);
            mat_polys.push(poly);
            points.push(sumcheck_point.clone());
            evals.push(eval);
        });
        // println!("mat_polys: {:?}\n", mat_polys);
        // println!("points: {:?}\n", points);
        // println!("evals: {:?}\n", evals);
        // println!("mat_polys.len(): {}\n", mat_polys.len());
        // println!("points.len(): {}\n", points.len());
        // println!("evals.len(): {}\n", evals.len());
        let pcs_proof_res = PCS::multi_open(
            &self.pcs_param,
            mat_polys.as_slice(),
            &points.as_slice(),
            &evals.as_slice(),
            &mut self.transcript,
        );
        let pcs_proof = match pcs_proof_res {
            Ok(p) => p,
            Err(e) => {
                println!("complile_proof errored during PCS multi_open proof");
                return Err(PolyIOPErrors::InvalidProver(e.to_string()));
            },
        };

        // 4) create the CompiledProof
        let mut sumcheck_val_map: HashMap<TrackerID, F> = HashMap::new();
        for claim in self.sum_check_claims.iter() {
            sumcheck_val_map.insert(claim.label.clone(), claim.claimed_sum);
        }
        let mut query_map: HashMap<(TrackerID, Vec<F>), F> = HashMap::new();
        mat_comm_ids.iter().for_each(|id| {
            query_map.insert((id.clone(), sumcheck_point.clone()), F::zero());
        });

        Ok(CompiledZKSQLProof {
            sumcheck_claims: sumcheck_val_map, /* need to tell verifier sum values from before
                                                * aggregation */
            sc_proof,
            sc_aux_info,
            query_map,
            comms: self.materialized_comms.clone(),
            pcs_proof: vec![pcs_proof],
        })
    }
}
