use std::io::Cursor;

use ark_piop::{
    errors::SnarkResult,
    prover::structs::proof::SNARKProof,
    setup::structs::{SNARKPk, SNARKVk},
    SnarkBackend,
};
use ark_serialize::{
    CanonicalDeserialize, CanonicalSerialize, Compress, SerializationError, Valid,
};
use derivative::Derivative;
use proof_planner::logical_plan_optimizer::OptimizationHints;
use tracing::debug;
use tt_core::errors::TTResult;
use zstd::stream::{decode_all as zstd_decode_all, encode_all as zstd_encode_all};

pub use ark_piop::artifact::Artifact;

/// Zstd compression level used when serializing `TTProof` artifacts.
///
/// Level `1` intentionally favors low prover-side latency while still giving a
/// strong size reduction on the serialized proof bytes.
const TTPROOF_ZSTD_LEVEL: i32 = 1;

/// The full truth-table proof that is sent from the prover to the verifier
#[derive(Derivative)]
#[derivative(Clone(bound = ""))]
pub struct TTProof<B: SnarkBackend> {
    /// The SNARK proof generated by the prover, sometimes noted as "Cryptographic proof" in documentation.
    snark_proof: SNARKProof<B>,
    /// The list of optimization hints used by the prover that is sent to the verifier, which should be used by the verifier to arrive to the same proof plan as the prover.
    optimization_hints: OptimizationHints,
}

/// The prover key for the truth-table
pub struct TTPk<B: SnarkBackend> {
    /// The SNARK prover key
    snark_pk: SNARKPk<B>,
}

/// The verifier key for the truth-table
pub struct TTVk<B: SnarkBackend> {
    /// The SNARK verifier key
    snark_vk: SNARKVk<B>,
}

impl<B: SnarkBackend> TTProof<B> {
    /// Create a new TTProof from the given SNARK proof and optimization hints.
    pub fn new(
        snark_proof: SNARKProof<B>,
        optimization_hints: OptimizationHints,
    ) -> TTResult<Self> {
        Ok(Self {
            snark_proof,
            optimization_hints,
        })
    }

    /// Move the SNARK proof out of the TTProof, discarding the optimization hints.
    pub fn snark_proof(self) -> SNARKProof<B> {
        self.snark_proof
    }

    /// Get a reference to the SNARK proof contained in the TTProof.
    pub fn as_snark_proof(&self) -> &SNARKProof<B> {
        &self.snark_proof
    }
    /// Move both the SNARK proof and the optimization hints out of the TTProof.
    pub fn into_parts(self) -> (SNARKProof<B>, OptimizationHints) {
        (self.snark_proof, self.optimization_hints)
    }

    /// Get a reference to the optimization hints contained in the TTProof.
    pub fn optimization_hints(&self) -> &OptimizationHints {
        &self.optimization_hints
    }

    pub fn snark_proof_size_breakdown_bytes(&self) -> SnarkProofSizeBreakdown
    where
        SNARKProof<B>: CanonicalSerialize,
    {
        let sc_subproof = self.snark_proof.sc_subproof.serialized_size(Compress::Yes);

        let mv_opening_proof = self
            .snark_proof
            .mv_pcs_subproof
            .opening_proof
            .serialized_size(Compress::Yes);
        let mv_commitments = self
            .snark_proof
            .mv_pcs_subproof
            .comitments
            .serialized_size(Compress::Yes);
        let mv_query_map = self
            .snark_proof
            .mv_pcs_subproof
            .query_map
            .serialized_size(Compress::Yes);
        let mv_pcs_subproof = self
            .snark_proof
            .mv_pcs_subproof
            .serialized_size(Compress::Yes);

        let uv_opening_proof = self
            .snark_proof
            .uv_pcs_subproof
            .opening_proof
            .serialized_size(Compress::Yes);
        let uv_commitments = self
            .snark_proof
            .uv_pcs_subproof
            .comitments
            .serialized_size(Compress::Yes);
        let uv_query_map = self
            .snark_proof
            .uv_pcs_subproof
            .query_map
            .serialized_size(Compress::Yes);
        let uv_pcs_subproof = self
            .snark_proof
            .uv_pcs_subproof
            .serialized_size(Compress::Yes);

        let miscellaneous_field_elements = self
            .snark_proof
            .miscellaneous_field_elements
            .serialized_size(Compress::Yes);
        let total = self.snark_proof.serialized_size(Compress::Yes);

        SnarkProofSizeBreakdown {
            sc_subproof,
            mv_pcs_subproof,
            mv_pcs_subproof_parts: PCSSubproofSizeBreakdown {
                opening_proof: mv_opening_proof,
                commitments: mv_commitments,
                query_map: mv_query_map,
                total: mv_pcs_subproof,
            },
            uv_pcs_subproof,
            uv_pcs_subproof_parts: PCSSubproofSizeBreakdown {
                opening_proof: uv_opening_proof,
                commitments: uv_commitments,
                query_map: uv_query_map,
                total: uv_pcs_subproof,
            },
            miscellaneous_field_elements,
            total,
        }
    }
}
#[derive(Clone, Copy, Debug)]
pub struct PCSSubproofSizeBreakdown {
    pub opening_proof: usize,
    pub commitments: usize,
    pub query_map: usize,
    pub total: usize,
}

#[derive(Clone, Copy, Debug)]
pub struct SnarkProofSizeBreakdown {
    pub sc_subproof: usize,
    pub mv_pcs_subproof: usize,
    pub mv_pcs_subproof_parts: PCSSubproofSizeBreakdown,
    pub uv_pcs_subproof: usize,
    pub uv_pcs_subproof_parts: PCSSubproofSizeBreakdown,
    pub miscellaneous_field_elements: usize,
    pub total: usize,
}

impl<B> Artifact for TTVk<B>
where
    B: SnarkBackend,
{
    fn to_bytes(&self) -> SnarkResult<Vec<u8>> {
        let mut buffer = Vec::new();
        self.snark_vk.serialize_uncompressed(&mut buffer)?;
        Ok(buffer)
    }

    fn from_bytes(bytes: &[u8]) -> SnarkResult<Self> {
        let mut cursor = Cursor::new(bytes);
        Ok(Self {
            snark_vk: SNARKVk::<B>::deserialize_uncompressed_unchecked(&mut cursor)?,
        })
    }
}

impl<B> Artifact for TTPk<B>
where
    B: SnarkBackend,
    SNARKPk<B>: CanonicalSerialize + CanonicalDeserialize,
{
    fn to_bytes(&self) -> SnarkResult<Vec<u8>> {
        let mut buffer = Vec::new();
        self.snark_pk.serialize_uncompressed(&mut buffer)?;
        Ok(buffer)
    }

    fn from_bytes(bytes: &[u8]) -> SnarkResult<Self> {
        let mut cursor = Cursor::new(bytes);
        Ok(Self {
            snark_pk: SNARKPk::<B>::deserialize_uncompressed_unchecked(&mut cursor)?,
        })
    }
}

impl<B> Artifact for TTProof<B>
where
    B: SnarkBackend,
    SNARKProof<B>: CanonicalSerialize + CanonicalDeserialize,
{
    fn to_bytes(&self) -> SnarkResult<Vec<u8>> {
        let mut raw_bytes = Vec::new();
        self.serialize_compressed(&mut raw_bytes)?;
        zstd_encode_all(Cursor::new(raw_bytes), TTPROOF_ZSTD_LEVEL).map_err(Into::into)
    }

    fn from_bytes(bytes: &[u8]) -> SnarkResult<Self> {
        if let Ok(decoded) = zstd_decode_all(Cursor::new(bytes)) {
            let mut cursor = Cursor::new(decoded.as_slice());
            return match Self::deserialize_compressed_unchecked(&mut cursor) {
                Ok(proof) => Ok(proof),
                Err(_) => {
                    let mut fallback_cursor = Cursor::new(decoded.as_slice());
                    Ok(Self::deserialize_uncompressed_unchecked(&mut fallback_cursor)?)
                }
            };
        }

        let mut cursor = Cursor::new(bytes);
        match Self::deserialize_compressed_unchecked(&mut cursor) {
            Ok(proof) => Ok(proof),
            Err(_) => {
                let mut fallback_cursor = Cursor::new(bytes);
                Ok(Self::deserialize_uncompressed_unchecked(&mut fallback_cursor)?)
            }
        }
    }
}

impl<B> TTVk<B>
where
    B: SnarkBackend,
{
    pub fn into_inner(self) -> SNARKVk<B> {
        self.snark_vk
    }

    pub fn as_inner(&self) -> &SNARKVk<B> {
        &self.snark_vk
    }
}

impl<B> TTPk<B>
where
    B: SnarkBackend,
{
    pub fn into_inner(self) -> SNARKPk<B> {
        self.snark_pk
    }

    pub fn as_inner(&self) -> &SNARKPk<B> {
        &self.snark_pk
    }
}

fn optimization_hints_payload_bytes(
    optimization_hints: &OptimizationHints,
) -> Result<Vec<u8>, SerializationError> {
    if optimization_hints.is_empty() {
        return Ok(Vec::new());
    }
    let payload = bincode::serialize(optimization_hints).map_err(|err| {
        debug!(
            ?err,
            "TTProof serialize: failed to serialize optimization hints"
        );
        SerializationError::InvalidData
    })?;
    let mut bytes = Vec::with_capacity(b"TTH1".len() + payload.len());
    bytes.extend_from_slice(b"TTH1");
    bytes.extend_from_slice(&payload);
    Ok(bytes)
}

/// Implementing the Valid trait for `TTProof` to allow for validation checks during deserialization if needed.
impl<B> Valid for TTProof<B>
where
    B: SnarkBackend,
{
    fn check(&self) -> Result<(), SerializationError> {
        Ok(())
    }
}

/// Implementing the canonical serialization for `TTProof`
impl<B> CanonicalSerialize for TTProof<B>
where
    B: SnarkBackend,
    SNARKProof<B>: CanonicalSerialize,
{
    fn serialize_with_mode<W: std::io::Write>(
        &self,
        mut writer: W,
        compress: Compress,
    ) -> Result<(), SerializationError> {
        let plan_bytes = optimization_hints_payload_bytes(&self.optimization_hints)?;
        let plan_len = plan_bytes.len() as u64;
        debug!(
            plan_len,
            "TTProof serialize: optimization-hint artifact byte length"
        );
        writer.write_all(&plan_len.to_le_bytes())?;
        writer.write_all(&plan_bytes)?;
        self.snark_proof
            .serialize_with_mode(&mut writer, compress)?;
        Ok(())
    }

    fn serialized_size(&self, compress: Compress) -> usize {
        let plan_len = optimization_hints_payload_bytes(&self.optimization_hints)
            .map(|bytes| bytes.len())
            .unwrap_or(0);
        8 + plan_len + self.snark_proof.serialized_size(compress)
    }
}

/// Implementing the canonical deserialization for `TTProof`
impl<B> CanonicalDeserialize for TTProof<B>
where
    B: SnarkBackend,
    SNARKProof<B>: CanonicalDeserialize,
{
    fn deserialize_with_mode<R: std::io::Read>(
        mut reader: R,
        compress: ark_serialize::Compress,
        _validate: ark_serialize::Validate,
    ) -> Result<Self, SerializationError> {
        let mut len_bytes = [0u8; 8];
        reader.read_exact(&mut len_bytes)?;
        let plan_len = u64::from_le_bytes(len_bytes) as usize;
        let mut plan_bytes = vec![0u8; plan_len];
        if plan_len > 0 {
            reader.read_exact(&mut plan_bytes)?;
        }
        let optimization_hints = if plan_len == 0 {
            OptimizationHints::default()
        } else if plan_bytes.starts_with(b"TTH1") {
            bincode::deserialize::<OptimizationHints>(&plan_bytes[b"TTH1".len()..])
                .map_err(|_| SerializationError::InvalidData)?
        } else {
            // Legacy proofs stored optimized IR bytes in this slot. We keep the
            // framing compatible, but new code no longer retains that payload.
            OptimizationHints::default()
        };
        let snark_proof = SNARKProof::<B>::deserialize_with_mode(reader, compress, _validate)?;
        Ok(Self {
            snark_proof,
            optimization_hints,
        })
    }
}
